# This is a basic workflow to help you get started with Actions

name: Deployment WorkFlow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        env: 
          CI: true
          persist-credentials: false
      
      - name: GitHub Action for committing changes to a repository
        
          
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'  
      
      - name: Deploy app
        uses: devops-infra/action-commit-push@0.1
        with:
          # Personal Access Token for GitHub for pushing the code
          github_token: b47f0e61e1e05b7f67d23f116d790187fafa2a57
        run: | 
          sudo chown -R $USER /home/runner/work/MyLife/
          git config --global user.name "HITESHGOEL08"
          yarn run deploy-workflow
